version: '3'
services:
  # web:
  #   build: .
  #   image: server
  #   container_name: server_web
  #   command: flask --app fsapp/test run --host=0.0.0.0
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - redis
  worker:
    build: .
    container_name: server_worker
    command: flask --app 'fsapp:create_app("dev",True)' rq worker -v default
    volumes:
    - /home/ec2-user/efs/code:/home/ec2-user/efs/code
    - ./instance:/cls-forwarding-service/instance
    depends_on:
      - redis
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data:delegated
    ports:
      - '6379:6379'
    expose:
      - '6379'
volumes:
  redis_data:
